In [1]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [2]:
import spacy

nlp = spacy.load("en_core_web_sm")

In [3]:
from transformers import pipeline
from transformers import AutoTokenizer, AutoModel

In [4]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [5]:
import pandas as pd
import numpy as np

In [6]:
import re

In [7]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
text = ["I love machine learning", "NLP is amazing"]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(text)

print(X.toarray())

[[0.         0.         0.57735027 0.57735027 0.57735027 0.        ]
 [0.57735027 0.57735027 0.         0.         0.         0.57735027]]

In [9]:
corpus = "Generative AI is a type of artificial intelligence that creates new content—including text, images, code, audio, and video—by learning patterns from existing data using deep learning models. It excels at generating original outputs based on prompts, moving beyond simple classification to create content similar to its training data. Popular tools like ChatGPT and Gemini use foundation models to transform workflows across industries. "

In [10]:
corpus

'Generative AI is a type of artificial intelligence that creates new content—including text, images, code, audio, and video—by learning patterns from existing data using deep learning models. It excels at generating original outputs based on prompts, moving beyond simple classification to create content similar to its training data. Popular tools like ChatGPT and Gemini use foundation models to transform workflows across industries. '

In [11]:
corpus.split('.')

['Generative AI is a type of artificial intelligence that creates new content—including text, images, code, audio, and video—by learning patterns from existing data using deep learning models',
 ' It excels at generating original outputs based on prompts, moving beyond simple classification to create content similar to its training data',
 ' Popular tools like ChatGPT and Gemini use foundation models to transform workflows across industries',
 ' ']

In [17]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [19]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [20]:
from nltk.tokenize import sent_tokenize

text = "Hello world. This is a test."
print(sent_tokenize(text))

['Hello world.', 'This is a test.']

**SENTANCE** **TOKENIZATION**

In [21]:
sent_tok = sent_tokenize(corpus)

In [22]:
sent_tok

['Generative AI is a type of artificial intelligence that creates new content—including text, images, code, audio, and video—by learning patterns from existing data using deep learning models.',
 'It excels at generating original outputs based on prompts, moving beyond simple classification to create content similar to its training data.',
 'Popular tools like ChatGPT and Gemini use foundation models to transform workflows across industries.']

In [23]:
len(sent_tok)

3

In [24]:

sent_tok[0]

'Generative AI is a type of artificial intelligence that creates new content—including text, images, code, audio, and video—by learning patterns from existing data using deep learning models.'

In [25]:
sent_tok[1]

'It excels at generating original outputs based on prompts, moving beyond simple classification to create content similar to its training data.'

In [26]:
from nltk.tokenize import word_tokenize

word_tok = word_tokenize(sent_tok[0])
print(word_tok)

['Generative', 'AI', 'is', 'a', 'type', 'of', 'artificial', 'intelligence', 'that', 'creates', 'new', 'content—including', 'text', ',', 'images', ',', 'code', ',', 'audio', ',', 'and', 'video—by', 'learning', 'patterns', 'from', 'existing', 'data', 'using', 'deep', 'learning', 'models', '.']

In [28]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [29]:
lst = ["aa","bb","cc"]

In [30]:
"".join(lst)

'aabbcc'

In [31]:
" ".join(lst)

'aa bb cc'

In [32]:
".  ".join(lst)

'aa.  bb.  cc'

In [33]:
"_".join(lst)

'aa_bb_cc'

In [34]:
" ".join(sent_tok)

'Generative AI is a type of artificial intelligence that creates new content—including text, images, code, audio, and video—by learning patterns from existing data using deep learning models. It excels at generating original outputs based on prompts, moving beyond simple classification to create content similar to its training data. Popular tools like ChatGPT and Gemini use foundation models to transform workflows across industries.'

WORD TOKENIZATION

In [35]:
word_tokens = word_tokenize(corpus)

In [36]:
print(word_tokens)

['Generative', 'AI', 'is', 'a', 'type', 'of', 'artificial', 'intelligence', 'that', 'creates', 'new', 'content—including', 'text', ',', 'images', ',', 'code', ',', 'audio', ',', 'and', 'video—by', 'learning', 'patterns', 'from', 'existing', 'data', 'using', 'deep', 'learning', 'models', '.', 'It', 'excels', 'at', 'generating', 'original', 'outputs', 'based', 'on', 'prompts', ',', 'moving', 'beyond', 'simple', 'classification', 'to', 'create', 'content', 'similar', 'to', 'its', 'training', 'data', '.', 'Popular', 'tools', 'like', 'ChatGPT', 'and', 'Gemini', 'use', 'foundation', 'models', 'to', 'transform', 'workflows', 'across', 'industries', '.']

In [37]:
" ".join(word_tokens)

'Generative AI is a type of artificial intelligence that creates new content—including text , images , code , audio , and video—by learning patterns from existing data using deep learning models . It excels at generating original outputs based on prompts , moving beyond simple classification to create content similar to its training data . Popular tools like ChatGPT and Gemini use foundation models to transform workflows across industries .'

In [38]:
# 2. Download all required NLTK resources (punkt, stopwords, wordnet, averaged_perceptron_tagger_eng) using nltk.download().
nltk.download('punkt_tab') #tokenisation
nltk.download('stopwords') #for stopords
nltk.download('wordnet') #for immutatization
nltk.download('averaged_perceptron_tagger')
nltk.download('movie_reviews')
print("yes")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.

yes

STEMMING AND LEMMATIZATION

In [39]:

ps = PorterStemmer()

In [41]:
ps.stem("prediction")

'predict'

In [42]:
ps.stem("Intelligence")

'intellig'

In [43]:
for word in word_tokens:
  stem_word = ps.stem(word)
  print(word,"--->",stem_word)

Generative ---> gener
AI ---> ai
is ---> is
a ---> a
type ---> type
of ---> of
artificial ---> artifici
intelligence ---> intellig
that ---> that
creates ---> creat
new ---> new
content—including ---> content—includ
text ---> text
, ---> ,
images ---> imag
, ---> ,
code ---> code
, ---> ,
audio ---> audio
, ---> ,
and ---> and
video—by ---> video—bi
learning ---> learn
patterns ---> pattern
from ---> from
existing ---> exist
data ---> data
using ---> use
deep ---> deep
learning ---> learn
models ---> model
. ---> .
It ---> it
excels ---> excel
at ---> at
generating ---> gener
original ---> origin
outputs ---> output
based ---> base
on ---> on
prompts ---> prompt
, ---> ,
moving ---> move
beyond ---> beyond
simple ---> simpl
classification ---> classif
to ---> to
create ---> creat
content ---> content
similar ---> similar
to ---> to
its ---> it
training ---> train
data ---> data
. ---> .
Popular ---> popular
tools ---> tool
like ---> like
ChatGPT ---> chatgpt
and ---> and
Gemini ---> gemini
use ---> use
foundation ---> foundat
models ---> model
to ---> to
transform ---> transform
workflows ---> workflow
across ---> across
industries ---> industri
. ---> .

In [44]:
from nltk.stem import WordNetLemmatizer

In [45]:
lm = WordNetLemmatizer()

In [47]:
lm.lemmatize("Intelligence")

'Intelligence'

In [48]:
lm.lemmatize("prediction" ,pos="n")

'prediction'

In [49]:
lm.lemmatize("predict" ,pos="v")

'predict'

In [50]:
for word in word_tokens:
  lemm_word = lm.lemmatize(word)
  print(word,"--->",lemm_word)

Generative ---> Generative
AI ---> AI
is ---> is
a ---> a
type ---> type
of ---> of
artificial ---> artificial
intelligence ---> intelligence
that ---> that
creates ---> creates
new ---> new
content—including ---> content—including
text ---> text
, ---> ,
images ---> image
, ---> ,
code ---> code
, ---> ,
audio ---> audio
, ---> ,
and ---> and
video—by ---> video—by
learning ---> learning
patterns ---> pattern
from ---> from
existing ---> existing
data ---> data
using ---> using
deep ---> deep
learning ---> learning
models ---> model
. ---> .
It ---> It
excels ---> excels
at ---> at
generating ---> generating
original ---> original
outputs ---> output
based ---> based
on ---> on
prompts ---> prompt
, ---> ,
moving ---> moving
beyond ---> beyond
simple ---> simple
classification ---> classification
to ---> to
create ---> create
content ---> content
similar ---> similar
to ---> to
its ---> it
training ---> training
data ---> data
. ---> .
Popular ---> Popular
tools ---> tool
like ---> like
ChatGPT ---> ChatGPT
and ---> and
Gemini ---> Gemini
use ---> use
foundation ---> foundation
models ---> model
to ---> to
transform ---> transform
workflows ---> workflow
across ---> across
industries ---> industry
. ---> .

STOWORDS IN NLTK

In [51]:
print(stopwords.words())

['tyre', 'rreth', 'le', 'atyre', 'këta', 'megjithëse', 'kemi', 'per', 'ndonëse', 'dytë', 'pse', 'tha', 'aty', 'ndaj', 'ke', 'këtë', 'duhet', 'pa', 'perket', 'veç', 'ndonje', 'një', 'keshtu', 's', 'janë', 'jane', 'ti', 'ia', 'megjithese', 'prej', 'ishte', 'tjerë', 'ai', 'se', 'tillë', 'do', 'si', 'ja', 'tonë', 'keta', 'pastaj', 'ndersa', 'siç', 'unë', 'gjate', 'di', 'kësaj', 'cilin', 'kjo', 'dhënë', 'da', 'teper', 'ketij', 'ama', 'pasi', 'fjalë', 'kanë', 'vetem', 'za', 'd.m.th.', 'ose', 'pas', 'ndonjë', 'cila', 'ndodhur', 'dyte', 'ardhur', 'kësi', 'nga', 'vete', 'atij', 'ta', 'jenë', 'rendit', 'tane', 'keso', 'deri', 'tone', 'të', 'prandaj', 'bëjë', 'domethënë', 'dhe', 'qi', 'mirepo', 'tona', 'që', 'u', 'këtu', 'cilet', 'jene', 'tjere', 'gjë', 'së', 'gjatë', 'duhej', 't', 'dhene', 'thuhet', 'po', 'une', 'dy', 'cfare', 'ndërsa', 'sepse', 'edhe', 'cilen', 'to', 'meqenese', 'meje', 'tij', 'qene', 'jeni', 'them', 'përket', 'keto', 'ni', 'këso', 'asaj', 'ajo', 'sic', 'vetëm', 'ketyre', 'andaj', 'na', 'sa', 'kesaj', 'cili', 'këtyre', 'domethene', 'mirëpo', 'cilën', 'mos', 'madh', 'qenë', 'cilët', 'thënë', 'jemi', 'fjale', 'soje', 'neve', 'gjitha', 'kështu', 'vet', 'kur', 'ty', 'meqë', 'meqenëse', 'jush', 'ketë', 'para', 'kush', 'i', 'mua', 'dite', 'ate', 'për', 'tepër', 'nesh', 'meqe', 'ketu', 'ku', 'disa', 'ato', 'mbi', 'gje', 'ne', 'është', 'tille', 'teje', 'megjithate', 'ju', 'nese', 'saj', 'ashtu', 'më', 'mbasi', 'te', 'thene', 'jo', 'ditë', 'nuk', 'gjithe', 'shume', 'nje', 'tanë', 'mund', 'aqsa', 'sot', 'këto', 'tjera', 'tjetër', 'tjeter', 'atë', 'kisha', 'megjithatë', 'këtij', 'nëse', 'dimë', 'eshte', 'vazhdojmë', 'ka', 'kam', 'kesi', 'je', 'vazhdojme', 'duke', 'dime', 'kinse', 'por', 'kane', 'pika', 'keni', 'beje', 'ky', 'parasysh', 'apo', 'gjithë', 'me', 'ata', 'çfarë', 'jam', 'juve', 'kete', 'a', 'pra', 'qe', 'tash', 'në', 'vetë', 'vec', 'as', 'ndonese', 'tani', 'pak', 'e', 'shumë', 'إذ', 'إذا', 'إذما', 'إذن', 'أف', 'أقل', 'أكثر', 'ألا', 'إلا', 'التي', 'الذي', 'الذين', 'اللاتي', 'اللائي', 'اللتان', 'اللتيا', 'اللتين', 'اللذان', 'اللذين', 'اللواتي', 'إلى', 'إليك', 'إليكم', 'إليكما', 'إليكن', 'أم', 'أما', 'أما', 'إما', 'أن', 'إن', 'إنا', 'أنا', 'أنت', 'أنتم', 'أنتما', 'أنتن', 'إنما', 'إنه', 'أنى', 'أنى', 'آه', 'آها', 'أو', 'أولاء', 'أولئك', 'أوه', 'آي', 'أي', 'أيها', 'إي', 'أين', 'أين', 'أينما', 'إيه', 'بخ', 'بس', 'بعد', 'بعض', 'بك', 'بكم', 'بكم', 'بكما', 'بكن', 'بل', 'بلى', 'بما', 'بماذا', 'بمن', 'بنا', 'به', 'بها', 'بهم', 'بهما', 'بهن', 'بي', 'بين', 'بيد', 'تلك', 'تلكم', 'تلكما', 'ته', 'تي', 'تين', 'تينك', 'ثم', 'ثمة', 'حاشا', 'حبذا', 'حتى', 'حيث', 'حيثما', 'حين', 'خلا', 'دون', 'ذا', 'ذات', 'ذاك', 'ذان', 'ذانك', 'ذلك', 'ذلكم', 'ذلكما', 'ذلكن', 'ذه', 'ذو', 'ذوا', 'ذواتا', 'ذواتي', 'ذي', 'ذين', 'ذينك', 'ريث', 'سوف', 'سوى', 'شتان', 'عدا', 'عسى', 'عل', 'على', 'عليك', 'عليه', 'عما', 'عن', 'عند', 'غير', 'فإذا', 'فإن', 'فلا', 'فمن', 'في', 'فيم', 'فيما', 'فيه', 'فيها', 'قد', 'كأن', 'كأنما', 'كأي', 'كأين', 'كذا', 'كذلك', 'كل', 'كلا', 'كلاهما', 'كلتا', 'كلما', 'كليكما', 'كليهما', 'كم', 'كم', 'كما', 'كي', 'كيت', 'كيف', 'كيفما', 'لا', 'لاسيما', 'لدى', 'لست', 'لستم', 'لستما', 'لستن', 'لسن', 'لسنا', 'لعل', 'لك', 'لكم', 'لكما', 'لكن', 'لكنما', 'لكي', 'لكيلا', 'لم', 'لما', 'لن', 'لنا', 'له', 'لها', 'لهم', 'لهما', 'لهن', 'لو', 'لولا', 'لوما', 'لي', 'لئن', 'ليت', 'ليس', 'ليسا', 'ليست', 'ليستا', 'ليسوا', 'ما', 'ماذا', 'متى', 'مذ', 'مع', 'مما', 'ممن', 'من', 'منه', 'منها', 'منذ', 'مه', 'مهما', 'نحن', 'نحو', 'نعم', 'ها', 'هاتان', 'هاته', 'هاتي', 'هاتين', 'هاك', 'هاهنا', 'هذا', 'هذان', 'هذه', 'هذي', 'هذين', 'هكذا', 'هل', 'هلا', 'هم', 'هما', 'هن', 'هنا', 'هناك', 'هنالك', 'هو', 'هؤلاء', 'هي', 'هيا', 'هيت', 'هيهات', 'والذي', 'والذين', 'وإذ', 'وإذا', 'وإن', 'ولا', 'ولكن', 'ولو', 'وما', 'ومن', 'وهو', 'يا', 'أبٌ', 'أخٌ', 'حمٌ', 'فو', 'أنتِ', 'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر', 'جانفي', 'فيفري', 'مارس', 'أفريل', 'ماي', 'جوان', 'جويلية', 'أوت', 'كانون', 'شباط', 'آذار', 'نيسان', 'أيار', 'حزيران', 'تموز', 'آب', 'أيلول', 'تشرين', 'دولار', 'دينار', 'ريال', 'درهم', 'ليرة', 'جنيه', 'قرش', 'مليم', 'فلس', 'هللة', 'سنتيم', 'يورو', 'ين', 'يوان', 'شيكل', 'واحد', 'اثنان', 'ثلاثة', 'أربعة', 'خمسة', 'ستة', 'سبعة', 'ثمانية', 'تسعة', 'عشرة', 'أحد', 'اثنا', 'اثني', 'إحدى', 'ثلاث', 'أربع', 'خمس', 'ست', 'سبع', 'ثماني', 'تسع', 'عشر', 'ثمان', 'سبت', 'أحد', 'اثنين', 'ثلاثاء', 'أربعاء', 'خميس', 'جمعة', 'أول', 'ثان', 'ثاني', 'ثالث', 'رابع', 'خامس', 'سادس', 'سابع', 'ثامن', 'تاسع', 'عاشر', 'حادي', 'أ', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', 'ء', 'ى', 'آ', 'ؤ', 'ئ', 'أ', 'ة', 'ألف', 'باء', 'تاء', 'ثاء', 'جيم', 'حاء', 'خاء', 'دال', 'ذال', 'راء', 'زاي', 'سين', 'شين', 'صاد', 'ضاد', 'طاء', 'ظاء', 'عين', 'غين', 'فاء', 'قاف', 'كاف', 'لام', 'ميم', 'نون', 'هاء', 'واو', 'ياء', 'همزة', 'ي', 'نا', 'ك', 'كن', 'ه', 'إياه', 'إياها', 'إياهما', 'إياهم', 'إياهن', 'إياك', 'إياكما', 'إياكم', 'إياك', 'إياكن', 'إياي', 'إيانا', 'أولالك', 'تانِ', 'تانِك', 'تِه', 'تِي', 'تَيْنِ', 'ثمّ', 'ثمّة', 'ذانِ', 'ذِه', 'ذِي', 'ذَيْنِ', 'هَؤلاء', 'هَاتانِ', 'هَاتِه', 'هَاتِي', 'هَاتَيْنِ', 'هَذا', 'هَذانِ', 'هَذِه', 'هَذِي', 'هَذَيْنِ', 'الألى', 'الألاء', 'أل', 'أنّى', 'أيّ', 'ّأيّان', 'أنّى', 'أيّ', 'ّأيّان', 'ذيت', 'كأيّ', 'كأيّن', 'بضع', 'فلان', 'وا', 'آمينَ', 'آهِ', 'آهٍ', 'آهاً', 'أُفٍّ', 'أُفٍّ', 'أفٍّ', 'أمامك', 'أمامكَ', 'أوّهْ', 'إلَيْكَ', 'إلَيْكَ', 'إليكَ', 'إليكنّ', 'إيهٍ', 'بخٍ', 'بسّ', 'بَسْ', 'بطآن', 'بَلْهَ', 'حاي', 'حَذارِ', 'حيَّ', 'حيَّ', 'دونك', 'رويدك', 'سرعان', 'شتانَ', 'شَتَّانَ', 'صهْ', 'صهٍ', 'طاق', 'طَق', 'عَدَسْ', 'كِخ', 'مكانَك', 'مكانَك', 'مكانَك', 'مكانكم', 'مكانكما', 'مكانكنّ', 'نَخْ', 'هاكَ', 'هَجْ', 'هلم', 'هيّا', 'هَيْهات', 'وا', 'واهاً', 'وراءَك', 'وُشْكَانَ', 'وَيْ', 'يفعلان', 'تفعلان', 'يفعلون', 'تفعلون', 'تفعلين', 'اتخذ', 'ألفى', 'تخذ', 'ترك', 'تعلَّم', 'جعل', 'حجا', 'حبيب', 'خال', 'حسب', 'خال', 'درى', 'رأى', 'زعم', 'صبر', 'ظنَّ', 'عدَّ', 'علم', 'غادر', 'ذهب', 'وجد', 'ورد', 'وهب', 'أسكن', 'أطعم', 'أعطى', 'رزق', 'زود', 'سقى', 'كسا', 'أخبر', 'أرى', 'أعلم', 'أنبأ', 'حدَث', 'خبَّر', 'نبَّا', 'أفعل به', 'ما أفعله', 'بئس', 'ساء', 'طالما', 'قلما', 'لات', 'لكنَّ', 'ءَ', 'أجل', 'إذاً', 'أمّا', 'إمّا', 'إنَّ', 'أنًّ', 'أى', 'إى', 'أيا', 'ب', 'ثمَّ', 'جلل', 'جير', 'رُبَّ', 'س', 'علًّ', 'ف', 'كأنّ', 'كلَّا', 'كى', 'ل', 'لات', 'لعلَّ', 'لكنَّ', 'لكنَّ', 'م', 'نَّ', 'هلّا', 'وا', 'أل', 'إلّا', 'ت', 'ك', 'لمّا', 'ن', 'ه', 'و', 'ا', 'ي', 'تجاه', 'تلقاء', 'جميع', 'حسب', 'سبحان', 'شبه', 'لعمر', 'مثل', 'معاذ', 'أبو', 'أخو', 'حمو', 'فو', 'مئة', 'مئتان', 'ثلاثمئة', 'أربعمئة', 'خمسمئة', 'ستمئة', 'سبعمئة', 'ثمنمئة', 'تسعمئة', 'مائة', 'ثلاثمائة', 'أربعمائة', 'خمسمائة', 'ستمائة', 'سبعمائة', 'ثمانمئة', 'تسعمائة', 'عشرون', 'ثلاثون', 'اربعون', 'خمسون', 'ستون', 'سبعون', 'ثمانون', 'تسعون', 'عشرين', 'ثلاثين', 'اربعين', 'خمسين', 'ستين', 'سبعين', 'ثمانين', 'تسعين', 'بضع', 'نيف', 'أجمع', 'جميع', 'عامة', 'عين', 'نفس', 'لا سيما', 'أصلا', 'أهلا', 'أيضا', 'بؤسا', 'بعدا', 'بغتة', 'تعسا', 'حقا', 'حمدا', 'خلافا', 'خاصة', 'دواليك', 'سحقا', 'سرا', 'سمعا', 'صبرا', 'صدقا', 'صراحة', 'طرا', 'عجبا', 'عيانا', 'غالبا', 'فرادى', 'فضلا', 'قاطبة', 'كثيرا', 'لبيك', 'معاذ', 'أبدا', 'إزاء', 'أصلا', 'الآن', 'أمد', 'أمس', 'آنفا', 'آناء', 'أنّى', 'أول', 'أيّان', 'تارة', 'ثمّ', 'ثمّة', 'حقا', 'صباح', 'مساء', 'ضحوة', 'عوض', 'غدا', 'غداة', 'قطّ', 'كلّما', 'لدن', 'لمّا', 'مرّة', 'قبل', 'خلف', 'أمام', 'فوق', 'تحت', 'يمين', 'شمال', 'ارتدّ', 'استحال', 'أصبح', 'أضحى', 'آض', 'أمسى', 'انقلب', 'بات', 'تبدّل', 'تحوّل', 'حار', 'رجع', 'راح', 'صار', 'ظلّ', 'عاد', 'غدا', 'كان', 'ما انفك', 'ما برح', 'مادام', 'مازال', 'مافتئ', 'ابتدأ', 'أخذ', 'اخلولق', 'أقبل', 'انبرى', 'أنشأ', 'أوشك', 'جعل', 'حرى', 'شرع', 'طفق', 'علق', 'قام', 'كرب', 'كاد', 'هبّa', 'ad', 'altı', 'altmış', 'amma', 'arasında', 'artıq', 'ay', 'az', 'bax', 'belə', 'bəli', 'bəlkə', 'beş', 'bəy', 'bəzən', 'bəzi', 'bilər', 'bir', 'biraz', 'biri', 'birşey', 'biz', 'bizim', 'bizlər', 'bu', 'buna', 'bundan', 'bunların', 'bunu', 'bunun', 'buradan', 'bütün', 'ci', 'cı', 'çox', 'cu', 'cü', 'çünki', 'da', 'daha', 'də', 'dedi', 'dək', 'dən', 'dəqiqə', 'deyil', 'dir', 'doqquz', 'doqsan', 'dörd', 'düz', 'ə', 'edən', 'edir', 'əgər', 'əlbəttə', 'elə', 'əlli', 'ən', 'əslində', 'et', 'etdi', 'etmə', 'etmək', 'faiz', 'gilə', 'görə', 'ha', 'haqqında', 'harada', 'hə', 'heç', 'həm', 'həmin', 'həmişə', 'hər', 'ı', 'idi', 'iki', 'il', 'ildə', 'ilə', 'ilk', 'in', 'indi', 'isə', 'istifadə', 'iyirmi', 'ki', 'kim', 'kimə', 'kimi', 'lakin', 'lap', 'məhz', 'mən', 'mənə', 'mirşey', 'nə', 'nəhayət', 'niyə', 'o', 'obirisi', 'of', 'olan', 'olar', 'olaraq', 'oldu', 'olduğu', 'olmadı', 'olmaz', 'olmuşdur', 'olsun', 'olur', 'on', 'ona', 'ondan', 'onlar', 'onlardan', 'onların ', 'onsuzda', 'onu', 'onun', 'oradan', 'otuz', 'öz', 'özü', 'qarşı', 'qədər', 'qırx', 'saat', 'sadəcə', 'saniyə', 'səhv', 'səkkiz', 'səksən', 'sən', 'sənə', 'sənin', 'siz', 'sizin', 'sizlər', 'sonra', 'təəssüf', 'ü', 'üç', 'üçün', 'var', 'və', 'xan', 'xanım', 'xeyr', 'ya', 'yalnız', 'yaxşı', 'yeddi', 'yenə', 'yəni', 'yetmiş', 'yox', 'yoxdur', 'yoxsa', 'yüz', 'zamanahala', 'aitzitik', 'al', 'ala ', 'alabadere', 'alabaina', 'alabaina', 'aldiz ', 'alta', 'amaitu', 'amaitzeko', 'anitz', 'antzina', 'arabera', 'arabera', 'arabera', 'argi', 'arratsaldero', 'arte', 'artean', 'asko', 'aspaldiko', 'aurrera', 'aurrera', 'azkenez', 'azkenik', 'azkenik', 'ba', 'bada', 'bada ', 'bada ', 'bada ', 'badarik', 'badarik', 'badarik ', 'badere', 'bai', 'baina', 'baina', 'baina ', 'baino', 'baino', 'baino', 'baino', 'baita', 'baizik ', 'baldin', 'baldin', 'barren', 'bat', 'batean', 'batean', 'batean', 'batean', 'batek', 'baten', 'batera', 'batez', 'bati', 'batzuei', 'batzuek', 'batzuetan', 'batzuk', 'bazen', 'bederen', 'bederik', 'beharrez', 'behiala', 'behin', 'behin', 'behin', 'behin', 'behinik', 'behinola', 'behintzat', 'bera', 'beraiek', 'beranduago', 'berau', 'berauek', 'beraz', 'beraz ', 'bere', 'berean', 'berebat', 'berehala', 'berori', 'beroriek', 'berriro', 'berriz', 'bertzalde', 'bertzenaz', 'bestalde', 'beste', 'bestela', 'besterik', 'bezain', 'bezala', 'bide', 'bien', 'bigarrenez', 'bigarrenik', 'bitartean', 'bitartean', 'bizkitartean', 'bukaeran', 'bukatzeko ', 'da', 'dago', 'dago', 'dela', 'dela', 'dela', 'delarik', 'den', 'dena', 'dena', 'dezadan', 'dira', 'ditu', 'du', 'dute', 'edo', 'edo ', 'edota ', 'egin', 'egin', 'egun', 'egun', 'egunean', 'emateko', 'era', 'erdi', 'ere', 'ere', 'ere', 'ere', 'ere ', 'esan', 'esan', 'esanak', 'esandakoaren', 'eta', 'eta', 'eta', 'eta', 'eta ', 'eta ', 'eurak', 'ez', 'ez ', 'ez ', 'eze ', 'ezen', 'ezer', 'ezezik', 'ezik', 'ezpabere ', 'ezpada ', 'ezpere', 'ezperen ', 'ezta', 'funtsean', 'gabe', 'gain', 'gainera ', 'gainera \t', 'gainerontzean ', 'gaur', 'gero', 'gero', 'gero', 'geroago', 'gisa', 'gu', 'gutxi', 'guzti', 'guztia', 'guztiz ', 'haatik', 'haiei', 'haiek', 'haietan', 'hain', 'hainbeste', 'hainbestez ', 'hala', 'hala', 'hala', 'halaber', 'halako', 'halatan', 'han', 'handik', 'hango', 'hara', 'hargatik', 'hari', 'hark', 'hartan', 'hartan', 'hasi', 'hasi', 'hasiera', 'hasieran', 'hasteaz', 'hasteko', 'hasteko', 'hau', 'hau', 'hau', 'hau', 'hau', 'hau', 'hauei', 'hauek', 'hauetan', 'hemen', 'hemendik', 'hemengo', 'hi', 'hona', 'honebestez', 'honek', 'honela', 'honela', 'honela', 'honen', 'honen', 'honetan', 'honetaz', 'honi', 'hor', 'hori', 'hori', 'hori', 'horiei', 'horiek', 'horietan', 'horko', 'horra \t', 'horratik', 'horregatik', 'horregatik', 'horrek', 'horrela', 'horrela', 'horrela', 'horren', 'horrenbestez', 'horretan', 'horri', 'hortaz', 'hortaz', 'hortik', 'hura', 'ikusi', 'ikusi', 'izan', 'izan', 'izan', 'jarraituz', 'kariaz', 'kasuaz', 'kontuan', 'laburbilduz', 'laburki', 'laster', 'laster', 'lehen', 'lehen', 'lehen', 'lehen', 'lehenengo', 'lehenengo', 'lehenik', 'lehen-lehenik', 'litzateke', 'medio', 'mendean', 'mundura', 'nahiz', 'ni', 'noiz', 'nola', 'non', 'nondik', 'nongo', 'nor', 'nora', 'on', 'ondoren', 'ondorio', 'ondorioz', 'ondorioz', 'orain', 'ordea ', 'orduan', 'orduan', 'orduan ', 'orduko', 'ordura', 'orobat', 'ostean', 'ostera', 'osterantzean ', 'pentsatuz', 'ustez', 'ze', 'zein', 'zein ', 'zen', 'zen', 'zenbait', 'zenbat', 'zer', 'zeren', 'zergatik', 'zergatik', 'ziren', 'zituen', 'zu', 'zuek', 'zuen', 'zuten', 'zuzen', 'на', 'не', 'што', 'па', 'да', 'за', 'як', 'для', 'гэта', 'ад', 'яго', 'аб', 'ён', 'калi', 'якiя', 'мы', 'больш', 'таксама', 'iх', 'толькi', 'пра', 'каб', 'гэтым', 'так', 'але', 'яшчэ', 'тым', 'якi', 'яе', 'пры', 'цi', 'яны', 'цяпер', 'таму', 'пасля', 'каля', 'гэтага', 'годзе', 'тыс', 'таго', 'тут', 'тысяч', 'ўжо', 'дзе', 'якая', 'са', 'яна', 'гэты', 'пад', 'можна', 'паводле', 'вельмi', 'ва', 'то', 'сёння', 'можа', 'ўсё', 'нас', 'вось', 'нават', 'або', 'сёлета', 'іх', 'той', 'ужо', 'чым', 'тое', 'хто', 'жа', 'без', 'праз', 'мяне', 'аднак', 'бо', 'мне', 'там', 'адзiн', 'два', 'сярод', 'гэтай', 'сябе', 'калі', 'толькі', 'дарэчы', 'млн', 'падчас', 'вы', 'усё', 'нашай', 'якія', 'iм', 'разам', 'акрамя', 'ды', 'якiх', 'мае', 'стала', 'раней', 'шмат', 'амаль', 'усе', 'першы', 'пакуль', 'напрыклад', 'тысячы', 'ўсе', 'ты', 'якой', 'раз', 'свае', 'iншых', 'гэтыя', 'тры', 'яму', 'які', 'сваю', 'памiж', 'ўсiх', 'ёй', 'сваёй', 'хоць', 'некалькi', 'аднаго', 'менавiта', 'проста', 'потым', 'нi', 'заўсёды', 'менш', 'тады', 'нам', 'свой', 'якiм', 'свята', 'такiм', 'перад', 'вядома', 'бы', 'якое', 'мая', 'тых', 'гэтых', 'такiя', 'зараз', 'адной', 'адна', 'адным', 'якога', 'добра', 'над', 'летась', 'справа', 'кожны', 'свайго', 'сваiх', 'неабходна', 'такiх', 'зноў', 'мiльёнаў', 'прычым', 'iншыя', 'днём', 'млрд', 'сам', 'ці', 'нашы', 'сабе', 'адразу', 'усяго', 'двух', 'тыя', 'нашых', 'якую', 'чаго', 'асаблiва', 'сваiм', 'першым', 'згодна', 'такое', 'найбольш', 'такi', 'дзве', 'ім', 'вельмі', 'наша', 'дзвюх', 'ну', 'сваё', 'праўда', 'вас', 'трох', 'зусiм', 'пяць', 'некаторыя', 'дык', 'крыху', 'чаму', 'такой', 'магчыма', 'сапраўды', 'такая', 'вам', 'нешта', 'усiх', 'адно', 'далей', 'значыць', 'чатыры', 'самых', 'хутка', 'самы', 'дзякуючы', 'наш', 'часта', 'самым', 'першай', 'адзін', 'супраць', 'яно', 'другi', 'удзень', 'нiчога', 'мой', 'побач', 'অতএব', 'অথচ', 'অথবা', 'অনুযায়ী', 'অনেক', 'অনেকে', 'অনেকেই', 'অন্তত', 'অন্য', 'অবধি', 'অবশ্য', 'অর্থাত', 'আই', 'আগামী', 'আগে', 'আগেই', 'আছে', 'আজ', 'আদ্যভাগে', 'আপনার', 'আপনি', 'আবার', 'আমরা', 'আমাকে', 'আমাদের', 'আমার', 'আমি', 'আর', 'আরও', 'ই', 'ইত্যাদি', 'ইহা', 'উচিত', 'উত্তর', 'উনি', 'উপর', 'উপরে', 'এ', 'এঁদের', 'এঁরা', 'এই', 'একই', 'একটি', 'একবার', 'একে', 'এক্', 'এখন', 'এখনও', 'এখানে', 'এখানেই', 'এটা', 'এটাই', 'এটি', 'এত', 'এতটাই', 'এতে', 'এদের', 'এব', 'এবং', 'এবার', 'এমন', 'এমনকী', 'এমনি', 'এর', 'এরা', 'এল', 'এস', 'এসে', 'ঐ', 'ও', 'ওঁদের', 'ওঁর', 'ওঁরা', 'ওই', 'ওকে', 'ওখানে', 'ওদের', 'ওর', 'ওরা', 'কখনও', 'কত', 'কবে', 'কমনে', 'কয়েক', 'কয়েকটি', 'করছে', 'করছেন', 'করতে', 'করবে', 'করবেন', 'করলে', 'করলেন', 'করা', 'করাই', 'করায়', 'করার', 'করি', 'করিতে', 'করিয়া', 'করিয়ে', 'করে', 'করেই', 'করেছিলেন', 'করেছে', 'করেছেন', 'করেন', 'কাউকে', 'কাছ', 'কাছে', 'কাজ', 'কাজে', 'কারও', 'কারণ', 'কি', 'কিংবা', 'কিছু', 'কিছুই', 'কিন্তু', 'কী', 'কে', 'কেউ', 'কেউই', 'কেখা', 'কেন', 'কোটি', 'কোন', 'কোনও', 'কোনো', 'ক্ষেত্রে', 'কয়েক', 'খুব', 'গিয়ে', 'গিয়েছে', 'গিয়ে', 'গুলি', 'গেছে', 'গেল', 'গেলে', 'গোটা', 'চলে', 'চান', 'চায়', 'চার', 'চালু', 'চেয়ে', 'চেষ্টা', 'ছাড়া', 'ছাড়াও', 'ছিল', 'ছিলেন', 'জন', 'জনকে', 'জনের', 'জন্য', 'জন্যওজে', 'জানতে', 'জানা', 'জানানো', 'জানায়', 'জানিয়ে', 'জানিয়েছে', 'জে', 'জ্নজন', 'টি', 'ঠিক', 'তখন', 'তত', 'তথা', 'তবু', 'তবে', 'তা', 'তাঁকে', 'তাঁদের', 'তাঁর', 'তাঁরা', 'তাঁাহারা', 'তাই', 'তাও', 'তাকে', 'তাতে', 'তাদের', 'তার', 'তারপর', 'তারা', 'তারৈ', 'তাহলে', 'তাহা', 'তাহাতে', 'তাহার', 'তিনঐ', 'তিনি', 'তিনিও', 'তুমি', 'তুলে', 'তেমন', 'তো', 'তোমার', 'থাকবে', 'থাকবেন', 'থাকা', 'থাকায়', 'থাকে', 'থাকেন', 'থেকে', 'থেকেই', 'থেকেও', 'দিকে', 'দিতে', 'দিন', 'দিয়ে', 'দিয়েছে', 'দিয়েছেন', 'দিলেন', 'দু', 'দুই', 'দুটি', 'দুটো', 'দেওয়া', 'দেওয়ার', 'দেওয়া', 'দেখতে', 'দেখা', 'দেখে', 'দেন', 'দেয়', 'দ্বারা', 'ধরা', 'ধরে', 'ধামার', 'নতুন', 'নয়', 'না', 'নাই', 'নাকি', 'নাগাদ', 'নানা', 'নিজে', 'নিজেই', 'নিজেদের', 'নিজের', 'নিতে', 'নিয়ে', 'নিয়ে', 'নেই', 'নেওয়া', 'নেওয়ার', 'নেওয়া', 'নয়', 'পক্ষে', 'পর', 'পরে', 'পরেই', 'পরেও', 'পর্যন্ত', 'পাওয়া', 'পাচ', 'পারি', 'পারে', 'পারেন', 'পি', 'পেয়ে', 'পেয়্র্', 'প্রতি', 'প্রথম', 'প্রভৃতি', 'প্রযন্ত', 'প্রাথমিক', 'প্রায়', 'প্রায়', 'ফলে', 'ফিরে', 'ফের', 'বক্তব্য', 'বদলে', 'বন', 'বরং', 'বলতে', 'বলল', 'বললেন', 'বলা', 'বলে', 'বলেছেন', 'বলেন', 'বসে', 'বহু', 'বা', 'বাদে', 'বার', 'বি', 'বিনা', 'বিভিন্ন', 'বিশেষ', 'বিষয়টি', 'বেশ', 'বেশি', 'ব্যবহার', 'ব্যাপারে', 'ভাবে', 'ভাবেই', 'মতো', 'মতোই', 'মধ্যভাগে', 'মধ্যে', 'মধ্যেই', 'মধ্যেও', 'মনে', 'মাত্র', 'মাধ্যমে', 'মোট', 'মোটেই', 'যখন', 'যত', 'যতটা', 'যথেষ্ট', 'যদি', 'যদিও', 'যা', 'যাঁর', 'যাঁরা', 'যাওয়া', 'যাওয়ার', 'যাওয়া', 'যাকে', 'যাচ্ছে', 'যাতে', 'যাদের', 'যান', 'যাবে', 'যায়', 'যার', 'যারা', 'যিনি', 'যে', 'যেখানে', 'যেতে', 'যেন', 'যেমন', 'র', 'রকম', 'রয়েছে', 'রাখা', 'রেখে', 'লক্ষ', 'শুধু', 'শুরু', 'সঙ্গে', 'সঙ্গেও', 'সব', 'সবার', 'সমস্ত', 'সম্প্রতি', 'সহ', 'সহিত', 'সাধারণ', 'সামনে', 'সি', 'সুতরাং', 'সে', 'সেই', 'সেখান', 'সেখানে', 'সেটা', 'সেটাই', 'সেটাও', 'সেটি', 'স্পষ্ট', 'স্বয়ং', 'হইতে', 'হইবে', 'হইয়া', 'হওয়া', 'হওয়ায়', 'হওয়ার', 'হচ্ছে', 'হত', 'হতে', 'হতেই', 'হন', 'হবে', 'হবেন', 'হয়', 'হয়তো', 'হয়নি', 'হয়ে', 'হয়েই', 'হয়েছিল', 'হয়েছে', 'হয়েছেন', 'হল', 'হলে', 'হলেই', 'হলেও', 'হলো', 'হাজার', 'হিসাবে', 'হৈলে', 'হোক', 'হয়a', 'abans', 'ací', 'ah', 'així', 'això', 'al', 'aleshores', 'algun', 'alguna', 'algunes', 'alguns', 'alhora', 'allà', 'allí', 'allò', 'als', 'altra', 'altre', 'altres', 'amb', 'ambdues', 'ambdós', 'anar', 'ans', 'apa', 'aquell', 'aquella', 'aquelles', 'aquells', 'aquest', 'aquesta', 'aquestes', 'aquests', 'aquí', 'baix', 'bastant', 'bé', 'cada', 'cadascuna', 'cadascunes', 'cadascuns', 'cadascú', 'com', 'consegueixo', 'conseguim', 'conseguir', 'consigueix', 'consigueixen', 'consigueixes', 'contra', "d'un", "d'una", "d'unes", "d'uns", 'dalt', 'de', 'del', 'dels', 'des', 'des de', 'després', 'dins', 'dintre', 'donat', 'doncs', 'durant', 'e', 'eh', 'el', 'elles', 'ells', 'els', 'em', 'en', 'encara', 'ens', 'entre', 'era', 'erem', 'eren', 'eres', 'es', 'esta', 'estan', 'estat', 'estava', 'estaven', 'estem', 'esteu', 'estic', 'està', 'estàvem', 'estàveu', 'et', 'etc', 'ets', 'fa', 'faig', 'fan', 'fas', 'fem', 'fer', 'feu', 'fi', 'fins', 'fora', 'gairebé', 'ha', 'han', 'has', 'haver', 'havia', 'he', 'hem', 'heu', 'hi', 'ho', 'i', 'igual', 'iguals', 'inclòs', 'ja', 'jo', "l'hi", 'la', 'les', 'li', "li'n", 'llarg', 'llavors', "m'he", 'ma', 'mal', 'malgrat', 'mateix', 'mateixa', 'mateixes', 'mateixos', 'me', 'mentre', 'meu', 'meus', 'meva', 'meves', 'mode', 'molt', 'molta', 'moltes', 'molts', 'mon', 'mons', 'més', "n'he", "n'hi", 'ne', 'ni', 'no', 'nogensmenys', 'només', 'nosaltres', 'nostra', 'nostre', 'nostres', 'o', 'oh', 'oi', 'on', 'pas', 'pel', 'pels', 'per', 'per que', 'perquè', 'però', 'poc', 'poca', 'pocs', 'podem', 'poden', 'poder', 'podeu', 'poques', 'potser', 'primer', 'propi', 'puc', 'qual', 'quals', 'quan', 'quant', 'que', 'quelcom', 'qui', 'quin', 'quina', 'quines', 'quins', 'què', "s'ha", "s'han", 'sa', 'sabem', 'saben', 'saber', 'sabeu', 'sap', 'saps', 'semblant', 'semblants', 'sense', 'ser', 'ses', 'seu', 'seus', 'seva', 'seves', 'si', 'sobre', 'sobretot', 'soc', 'solament', 'sols', 'som', 'son', 'sons', 'sota', 'sou', 'sóc', 'són', "t'ha", "t'han", "t'he", 'ta', 'tal', 'també', 'tampoc', 'tan', 'tant', 'tanta', 'tantes', 'te', 'tene', 'tenim', 'tenir', 'teniu', 'teu', 'teus', 'teva', 'teves', 'tinc', 'ton', 'tons', 'tot', 'tota', 'totes', 'tots', 'un', 'una', 'unes', 'uns', 'us', 'va', 'vaig', 'vam', 'van', 'vas', 'veu', 'vosaltres', 'vostra', 'vostre', 'vostres', 'érem', 'éreu', 'és', 'éssent', 'últim', 'ús一', '一下', '一些', '一切', '一则', '一天', '一定', '一方面', '一旦', '一时', '一来', '一样', '一次', '一片', '一直', '一致', '一般', '一起', '一边', '一面', '万一', '上下', '上升', '上去', '上来', '上述', '上面', '下列', '下去', '下来', '下面', '不一', '不久', '不仅', '不会', '不但', '不光', '不单', '不变', '不只', '不可', '不同', '不够', '不如'

In [52]:
print(stopwords.words("english"))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [53]:
print(stopwords.words("tamil"))

['அங்கு', 'அங்கே', 'அடுத்த', 'அதனால்', 'அதன்', 'அதற்கு', 'அதிக', 'அதில்', 'அது', 'அதே', 'அதை', 'அந்த', 'அந்தக்', 'அந்தப்', 'அன்று', 'அல்லது', 'அவன்', 'அவரது', 'அவர்', 'அவர்கள்', 'அவள்', 'அவை', 'ஆகிய', 'ஆகியோர்', 'ஆகும்', 'இங்கு', 'இங்கே', 'இடத்தில்', 'இடம்', 'இதனால்', 'இதனை', 'இதன்', 'இதற்கு', 'இதில்', 'இது', 'இதை', 'இந்த', 'இந்தக்', 'இந்தத்', 'இந்தப்', 'இன்னும்', 'இப்போது', 'இரு', 'இருக்கும்', 'இருந்த', 'இருந்தது', 'இருந்து', 'இவர்', 'இவை', 'உன்', 'உள்ள', 'உள்ளது', 'உள்ளன', 'எந்த', 'என', 'எனக்', 'எனக்கு', 'எனப்படும்', 'எனவும்', 'எனவே', 'எனினும்', 'எனும்', 'என்', 'என்ன', 'என்னும்', 'என்பது', 'என்பதை', 'என்ற', 'என்று', 'என்றும்', 'எல்லாம்', 'ஏன்', 'ஒரு', 'ஒரே', 'ஓர்', 'கொண்ட', 'கொண்டு', 'கொள்ள', 'சற்று', 'சிறு', 'சில', 'சேர்ந்த', 'தனது', 'தன்', 'தவிர', 'தான்', 'நான்', 'நாம்', 'நீ', 'பற்றி', 'பற்றிய', 'பல', 'பலரும்', 'பல்வேறு', 'பின்', 'பின்னர்', 'பிற', 'பிறகு', 'பெரும்', 'பேர்', 'போது', 'போன்ற', 'போல', 'போல்', 'மட்டுமே', 'மட்டும்', 'மற்ற', 'மற்றும்', 'மிக', 'மிகவும்', 'மீது', 'முதல்', 'முறை', 'மேலும்', 'மேல்', 'யார்', 'வந்த', 'வந்து', 'வரும்', 'வரை', 'வரையில்', 'விட', 'விட்டு', 'வேண்டும்', 'வேறு']

In [55]:
print(stopwords.words("hinglish"))

['a', 'aadi', 'aaj', 'aap', 'aapne', 'aata', 'aati', 'aaya', 'aaye', 'ab', 'abbe', 'abbey', 'abe', 'abhi', 'able', 'about', 'above', 'accha', 'according', 'accordingly', 'acha', 'achcha', 'across', 'actually', 'after', 'afterwards', 'again', 'against', 'agar', 'ain', 'aint', "ain't", 'aisa', 'aise', 'aisi', 'alag', 'all', 'allow', 'allows', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'an', 'and', 'andar', 'another', 'any', 'anybody', 'anyhow', 'anyone', 'anything', 'anyway', 'anyways', 'anywhere', 'ap', 'apan', 'apart', 'apna', 'apnaa', 'apne', 'apni', 'appear', 'are', 'aren', 'arent', "aren't", 'around', 'arre', 'as', 'aside', 'ask', 'asking', 'at', 'aur', 'avum', 'aya', 'aye', 'baad', 'baar', 'bad', 'bahut', 'bana', 'banae', 'banai', 'banao', 'banaya', 'banaye', 'banayi', 'banda', 'bande', 'bandi', 'bane', 'bani', 'bas', 'bata', 'batao', 'bc', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'best', 'better', 'between', 'beyond', 'bhai', 'bheetar', 'bhi', 'bhitar', 'bht', 'bilkul', 'bohot', 'bol', 'bola', 'bole', 'boli', 'bolo', 'bolta', 'bolte', 'bolti', 'both', 'brief', 'bro', 'btw', 'but', 'by', 'came', 'can', 'cannot', 'cant', "can't", 'cause', 'causes', 'certain', 'certainly', 'chahiye', 'chaiye', 'chal', 'chalega', 'chhaiye', 'clearly', "c'mon", 'com', 'come', 'comes', 'could', 'couldn', 'couldnt', "couldn't", 'd', 'de', 'dede', 'dega', 'degi', 'dekh', 'dekha', 'dekhe', 'dekhi', 'dekho', 'denge', 'dhang', 'di', 'did', 'didn', 'didnt', "didn't", 'dijiye', 'diya', 'diyaa', 'diye', 'diyo', 'do', 'does', 'doesn', 'doesnt', "doesn't", 'doing', 'done', 'dono', 'dont', "don't", 'doosra', 'doosre', 'down', 'downwards', 'dude', 'dunga', 'dungi', 'during', 'dusra', 'dusre', 'dusri', 'dvaara', 'dvara', 'dwaara', 'dwara', 'each', 'edu', 'eg', 'eight', 'either', 'ek', 'else', 'elsewhere', 'enough', 'etc', 'even', 'ever', 'every', 'everybody', 'everyone', 'everything', 'everywhere', 'ex', 'exactly', 'example', 'except', 'far', 'few', 'fifth', 'fir', 'first', 'five', 'followed', 'following', 'follows', 'for', 'forth', 'four', 'from', 'further', 'furthermore', 'gaya', 'gaye', 'gayi', 'get', 'gets', 'getting', 'ghar', 'given', 'gives', 'go', 'goes', 'going', 'gone', 'good', 'got', 'gotten', 'greetings', 'haan', 'had', 'hadd', 'hadn', 'hadnt', "hadn't", 'hai', 'hain', 'hamara', 'hamare', 'hamari', 'hamne', 'han', 'happens', 'har', 'hardly', 'has', 'hasn', 'hasnt', "hasn't", 'have', 'haven', 'havent', "haven't", 'having', 'he', 'hello', 'help', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', "here's", 'hereupon', 'hers', 'herself', "he's", 'hi', 'him', 'himself', 'his', 'hither', 'hm', 'hmm', 'ho', 'hoga', 'hoge', 'hogi', 'hona', 'honaa', 'hone', 'honge', 'hongi', 'honi', 'hopefully', 'hota', 'hotaa', 'hote', 'hoti', 'how', 'howbeit', 'however', 'hoyenge', 'hoyengi', 'hu', 'hua', 'hue', 'huh', 'hui', 'hum', 'humein', 'humne', 'hun', 'huye', 'huyi', 'i', "i'd", 'idk', 'ie', 'if', "i'll", "i'm", 'imo', 'in', 'inasmuch', 'inc', 'inhe', 'inhi', 'inho', 'inka', 'inkaa', 'inke', 'inki', 'inn', 'inner', 'inse', 'insofar', 'into', 'inward', 'is', 'ise', 'isi', 'iska', 'iskaa', 'iske', 'iski', 'isme', 'isn', 'isne', 'isnt', "isn't", 'iss', 'isse', 'issi', 'isski', 'it', "it'd", "it'll", 'itna', 'itne', 'itni', 'itno', 'its', "it's", 'itself', 'ityaadi', 'ityadi', "i've", 'ja', 'jaa', 'jab', 'jabh', 'jaha', 'jahaan', 'jahan', 'jaisa', 'jaise', 'jaisi', 'jata', 'jayega', 'jidhar', 'jin', 'jinhe', 'jinhi', 'jinho', 'jinhone', 'jinka', 'jinke', 'jinki', 'jinn', 'jis', 'jise', 'jiska', 'jiske', 'jiski', 'jisme', 'jiss', 'jisse', 'jitna', 'jitne', 'jitni', 'jo', 'just', 'jyaada', 'jyada', 'k', 'ka', 'kaafi', 'kab', 'kabhi', 'kafi', 'kaha', 'kahaa', 'kahaan', 'kahan', 'kahi', 'kahin', 'kahte', 'kaisa', 'kaise', 'kaisi', 'kal', 'kam', 'kar', 'kara', 'kare', 'karega', 'karegi', 'karen', 'karenge', 'kari', 'karke', 'karna', 'karne', 'karni', 'karo', 'karta', 'karte', 'karti', 'karu', 'karun', 'karunga', 'karungi', 'kaun', 'kaunsa', 'kayi', 'kch', 'ke', 'keep', 'keeps', 'keh', 'kehte', 'kept', 'khud', 'ki', 'kin', 'kine', 'kinhe', 'kinho', 'kinka', 'kinke', 'kinki', 'kinko', 'kinn', 'kino', 'kis', 'kise', 'kisi', 'kiska', 'kiske', 'kiski', 'kisko', 'kisliye', 'kisne', 'kitna', 'kitne', 'kitni', 'kitno', 'kiya', 'kiye', 'know', 'known', 'knows', 'ko', 'koi', 'kon', 'konsa', 'koyi', 'krna', 'krne', 'kuch', 'kuchch', 'kuchh', 'kul', 'kull', 'kya', 'kyaa', 'kyu', 'kyuki', 'kyun', 'kyunki', 'lagta', 'lagte', 'lagti', 'last', 'lately', 'later', 'le', 'least', 'lekar', 'lekin', 'less', 'lest', 'let', "let's", 'li', 'like', 'liked', 'likely', 'little', 'liya', 'liye', 'll', 'lo', 'log', 'logon', 'lol', 'look', 'looking', 'looks', 'ltd', 'lunga', 'm', 'maan', 'maana', 'maane', 'maani', 'maano', 'magar', 'mai', 'main', 'maine', 'mainly', 'mana', 'mane', 'mani', 'mano', 'many', 'mat', 'may', 'maybe', 'me', 'mean', 'meanwhile', 'mein', 'mera', 'mere', 'merely', 'meri', 'might', 'mightn', 'mightnt', "mightn't", 'mil', 'mjhe', 'more', 'moreover', 'most', 'mostly', 'much', 'mujhe', 'must', 'mustn', 'mustnt', "mustn't", 'my', 'myself', 'na', 'naa', 'naah', 'nahi', 'nahin', 'nai', 'name', 'namely', 'nd', 'ne', 'near', 'nearly', 'necessary', 'neeche', 'need', 'needn', 'neednt', "needn't", 'needs', 'neither', 'never', 'nevertheless', 'new', 'next', 'nhi', 'nine', 'no', 'nobody', 'non', 'none', 'noone', 'nope', 'nor', 'normally', 'not', 'nothing', 'novel', 'now', 'nowhere', 'o', 'obviously', 'of', 'off', 'often', 'oh', 'ok', 'okay', 'old', 'on', 'once', 'one', 'ones', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'ought', 'our', 'ours', 'ourselves', 'out', 'outside', 'over', 'overall', 'own', 'par', 'pata', 'pe', 'pehla', 'pehle', 'pehli', 'people', 'per', 'perhaps', 'phla', 'phle', 'phli', 'placed', 'please', 'plus', 'poora', 'poori', 'provides', 'pura', 'puri', 'q', 'que', 'quite', 'raha', 'rahaa', 'rahe', 'rahi', 'rakh', 'rakha', 'rakhe', 'rakhen', 'rakhi', 'rakho', 'rather', 're', 'really', 'reasonably', 'regarding', 'regardless', 'regards', 'rehte', 'rha', 'rhaa', 'rhe', 'rhi', 'ri', 'right', 's', 'sa', 'saara', 'saare', 'saath', 'sab', 'sabhi', 'sabse', 'sahi', 'said', 'sakta', 'saktaa', 'sakte', 'sakti', 'same', 'sang', 'sara', 'sath', 'saw', 'say', 'saying', 'says', 'se', 'second', 'secondly', 'see', 'seeing', 'seem', 'seemed', 'seeming', 'seems', 'seen', 'self', 'selves', 'sensible', 'sent', 'serious', 'seriously', 'seven', 'several', 'shall', 'shan', 'shant', "shan't", 'she', "she's", 'should', 'shouldn', 'shouldnt', "shouldn't", "should've", 'si', 'since', 'six', 'so', 'soch', 'some', 'somebody', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhat', 'somewhere', 'soon', 'still', 'sub', 'such', 'sup', 'sure', 't', 'tab', 'tabh', 'tak', 'take', 'taken', 'tarah', 'teen', 'teeno', 'teesra', 'teesre', 'teesri', 'tell', 'tends', 'tera', 'tere', 'teri', 'th', 'tha', 'than', 'thank', 'thanks', 'thanx', 'that', "that'll", 'thats', "that's", 'the', 'theek', 'their', 'theirs', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'therefore', 'therein', 'theres', "there's", 'thereupon', 'these', 'they', "they'd", "they'll", "they're", "they've", 'thi', 'thik', 'thing', 'think', 'thinking', 'third', 'this', 'tho', 'thoda', 'thodi', 'thorough', 'thoroughly', 'those', 'though', 'thought', 'three', 'through', 'throughout', 'thru', 'thus', 'tjhe', 'to', 'together', 'toh', 'too', 'took', 'toward', 'towards', 'tried', 'tries', 'true', 'truly', 'try', 'trying', 'tu', 'tujhe', 'tum', 'tumhara', 'tumhare', 'tumhari', 'tune', 'twice', 'two', 'um', 'umm', 'un', 'under', 'unhe', 'unhi', 'unho', 'unhone', 'unka', 'unkaa', 'unke', 'unki', 'unko', 'unless', 'unlikely', 'unn', 'unse', 'until', 'unto', 'up', 'upar', 'upon', 'us', 'use', 'used', 'useful', 'uses', 'usi', 'using', 'uska', 'uske', 'usne', 'uss', 'usse', 'ussi', 'usually', 'vaala', 'vaale', 'vaali', 'vahaan', 'vahan', 'vahi', 'vahin', 'vaisa', 'vaise', 'vaisi', 'vala', 'vale', 'vali', 'various', 've', 'very', 'via', 'viz', 'vo', 'waala', 'waale', 'waali', 'wagaira', 'wagairah', 'wagerah', 'waha', 'wahaan', 'wahan', 'wahi', 'wahin', 'waisa', 'waise', 'waisi', 'wala', 'wale', 'wali', 'want', 'wants', 'was', 'wasn', 'wasnt', "wasn't", 'way', 'we', "we'd", 'well', "we'll", 'went', 'were', "we're", 'weren', 'werent', "weren't", "we've", 'what', 'whatever', "what's", 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', "where's", 'whereupon', 'wherever', 'whether', 'which', 'while', 'who', 'whoever', 'whole', 'whom', "who's", 'whose', 'why', 'will', 'willing', 'with', 'within', 'without', 'wo', 'woh', 'wohi', 'won', 'wont', "won't", 'would', 'wouldn', 'wouldnt', "wouldn't", 'y', 'ya', 'yadi', 'yah', 'yaha', 'yahaan', 'yahan', 'yahi', 'yahin', 'ye', 'yeah', 'yeh', 'yehi', 'yes', 'yet', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've", 'yup']

In [56]:
len(stopwords.words("english"))

198

In [57]:
stp_words= stopwords.words("english")

In [58]:
"Is".lower() in stp_words

True

In [ ]:
for sentance in sent_tok:
  word_tok = word_tokenize(sentance)

In [59]:
word_tokenize(sent_tok[0])

['Generative',
 'AI',
 'is',
 'a',
 'type',
 'of',
 'artificial',
 'intelligence',
 'that',
 'creates',
 'new',
 'content—including',
 'text',
 ',',
 'images',
 ',',
 'code',
 ',',
 'audio',
 ',',
 'and',
 'video—by',
 'learning',
 'patterns',
 'from',
 'existing',
 'data',
 'using',
 'deep',
 'learning',
 'models',
 '.']

In [60]:
[lm.lemmatize(word,pos ="v")for word in word_tokens]

['Generative',
 'AI',
 'be',
 'a',
 'type',
 'of',
 'artificial',
 'intelligence',
 'that',
 'create',
 'new',
 'content—including',
 'text',
 ',',
 'image',
 ',',
 'code',
 ',',
 'audio',
 ',',
 'and',
 'video—by',
 'learn',
 'pattern',
 'from',
 'exist',
 'data',
 'use',
 'deep',
 'learn',
 'model',
 '.',
 'It',
 'excel',
 'at',
 'generate',
 'original',
 'output',
 'base',
 'on',
 'prompt',
 ',',
 'move',
 'beyond',
 'simple',
 'classification',
 'to',
 'create',
 'content',
 'similar',
 'to',
 'its',
 'train',
 'data',
 '.',
 'Popular',
 'tool',
 'like',
 'ChatGPT',
 'and',
 'Gemini',
 'use',
 'foundation',
 'model',
 'to',
 'transform',
 'workflows',
 'across',
 'industries',
 '.']

In [63]:
[lm.lemmatize(word,pos ="v")for word in word_tokens if word.lower()not in stp_words]

['Generative',
 'AI',
 'type',
 'artificial',
 'intelligence',
 'create',
 'new',
 'content—including',
 'text',
 ',',
 'image',
 ',',
 'code',
 ',',
 'audio',
 ',',
 'video—by',
 'learn',
 'pattern',
 'exist',
 'data',
 'use',
 'deep',
 'learn',
 'model',
 '.',
 'excel',
 'generate',
 'original',
 'output',
 'base',
 'prompt',
 ',',
 'move',
 'beyond',
 'simple',
 'classification',
 'create',
 'content',
 'similar',
 'train',
 'data',
 '.',
 'Popular',
 'tool',
 'like',
 'ChatGPT',
 'Gemini',
 'use',
 'foundation',
 'model',
 'transform',
 'workflows',
 'across',
 'industries',
 '.']

In [64]:
" ".join([lm.lemmatize(word,pos ="v")for word in word_tokens if word.lower()not in stp_words]
)

'Generative AI type artificial intelligence create new content—including text , image , code , audio , video—by learn pattern exist data use deep learn model . excel generate original output base prompt , move beyond simple classification create content similar train data . Popular tool like ChatGPT Gemini use foundation model transform workflows across industries .'

In [66]:
processed_sent = []
for sentance in sent_tok:
  word_tokens = word_tokenize(sentance)
  lemmatized_words= [lm.lemmatize(word,pos ="v")for word in word_tokens if word.lower()not in stp_words]
  processed_sent.append(" ".join(lemmatized_words))

In [67]:
processed_sent

['Generative AI type artificial intelligence create new content—including text , image , code , audio , video—by learn pattern exist data use deep learn model .',
 'excel generate original output base prompt , move beyond simple classification create content similar train data .',
 'Popular tool like ChatGPT Gemini use foundation model transform workflows across industries .']

In [68]:
import string

In [69]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [70]:
Sent_1 = "Hello, World! Python is amazing."

In [75]:
translator = str.maketrans('','',string.punctuation)
translator

{33: None,
 34: None,
 35: None,
 36: None,
 37: None,
 38: None,
 39: None,
 40: None,
 41: None,
 42: None,
 43: None,
 44: None,
 45: None,
 46: None,
 47: None,
 58: None,
 59: None,
 60: None,
 61: None,
 62: None,
 63: None,
 64: None,
 91: None,
 92: None,
 93: None,
 94: None,
 95: None,
 96: None,
 123: None,
 124: None,
 125: None,
 126: None}

In [71]:
ord("!")

33

In [72]:
ord("a")

97

In [76]:
Sent_1.translate(translator)

'Hello World Python is amazing'

In [79]:
processed_sent = []
for sentance in sent_tok:
  word_tokens = word_tokenize(sentance)
  lemmatized_words= [lm.lemmatize(word,pos ="v")for word in word_tokens if word.lower()not in stp_words]
  processed_sent.append(" ".join(lemmatized_words).translate(translator).strip())

In [80]:
processed_sent

['Generative AI type artificial intelligence create new content—including text  image  code  audio  video—by learn pattern exist data use deep learn model',
 'excel generate original output base prompt  move beyond simple classification create content similar train data',
 'Popular tool like ChatGPT Gemini use foundation model transform workflows across industries']

POS : PART OF SPEECH

In [81]:
# Common Parts of Speech Tags:
# 	•	Noun (NN): Person, place, or thing (e.g., cat, happiness)
# 	•	Pronoun (PRP): He, she, it
# 	•	Verb (VB): Actions or states (e.g., run, is)
# 	•	Adjective (JJ): Describes nouns (e.g., beautiful, large)
# 	•	Adverb (RB): Describes verbs or adjectives (e.g., quickly, very)
# 	•	Preposition (IN): Shows relationship (e.g., on, at, in)
# 	•	Conjunction (CC): Connects words or sentences (e.g., and, but)
# 	•	Determiner (DT): Specifies a noun (e.g., the, some)
# 	•	Interjection (UH): Expresses emotion (e.g., wow, oh)
# 	•	Proper Noun (NNP): Names (e.g., John, India)

In [84]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [85]:
nltk.pos_tag({"John"})

[('John', 'NNP')]

In [86]:
lemmatized_words

['Popular',
 'tool',
 'like',
 'ChatGPT',
 'Gemini',
 'use',
 'foundation',
 'model',
 'transform',
 'workflows',
 'across',
 'industries',
 '.']

In [87]:
nltk.pos_tag_sents([lemmatized_words])

[[('Popular', 'JJ'),
  ('tool', 'NN'),
  ('like', 'IN'),
  ('ChatGPT', 'NNP'),
  ('Gemini', 'NNP'),
  ('use', 'NN'),
  ('foundation', 'NN'),
  ('model', 'NN'),
  ('transform', 'NN'),
  ('workflows', 'VBZ'),
  ('across', 'IN'),
  ('industries', 'NNS'),
  ('.', '.')]]

NAMED Entity Recognization

In [88]:
# Common NER Categories:
# 	•	Person (PER): Names of people (e.g., Elon Musk, Marie Curie)
# 	•	Organization (ORG): Companies, institutions, or agencies (e.g., Google, United Nations)
# 	•	Location (LOC): Cities, countries, or geographical landmarks (e.g., Paris, Mount Everest)
# 	•	Date (DATE): Specific dates or periods (e.g., January 2023, 21st century)
# 	•	Time (TIME): Time expressions (e.g., 2:00 PM, morning)
# 	•	Money (MONEY): Monetary values (e.g., $500, €10 million)
# 	•	Percent (PERCENT): Percentages (e.g., 20%, 85%)
# 	•	Event (EVENT): Named events (e.g., Olympics, World War II)
# 	•	Product (PRODUCT): Items or brands (e.g., iPhone, Tesla Model S)
# 	•	Miscellaneous (MISC): Entities that don’t fit standard categories

In [89]:
text = "Sundar Pichai became the CEO of Google in 2015, and he was born in Chennai, India."

In [90]:
text

'Sundar Pichai became the CEO of Google in 2015, and he was born in Chennai, India.'

In [91]:
doc = nlp(text)

In [92]:
doc

Sundar Pichai became the CEO of Google in 2015, and he was born in Chennai, India.

In [93]:
doc.ents

(Sundar Pichai, Google, 2015, Chennai, India)

In [94]:
doc.ents[0].label_

'PERSON'

In [95]:
doc.ents[1].label_

'ORG'

In [96]:
for ent in doc.ents:
  print(ent,"----->",ent.label_)

Sundar Pichai -----> PERSON
Google -----> ORG
2015 -----> DATE
Chennai -----> GPE
India -----> GPE

In [97]:
from spacy import displacy

In [98]:
displacy.serve(doc,auto_select_port=True)

/usr/local/lib/python3.12/dist-packages/spacy/displacy/__init__.py:107: UserWarning: [W011] It looks like you're calling displacy.serve from within a Jupyter notebook or a similar environment. This likely means you're already running a local web server, so there's no need to make displaCy start another one. Instead, you should be able to replace displacy.serve with displacy.render to show the visualization.
  warnings.warn(Warnings.W011)

Using the 'dep' visualizer
Serving on http://0.0.0.0:5000 ...

Shutting down server on port 5000.

In [99]:
displacy.serve(doc,style="ent",auto_select_port=True)

Using the 'ent' visualizer
Serving on http://0.0.0.0:5000 ...

Shutting down server on port 5000.

VECTORIAZATION
1.BOW
2.TF-IDF


EMBEDDINGS

1.WORD2VEC(CBOW,SKIP-GRAM)
2.GLOVE(CO-OCCURANCE MATRIX)

BOW

In [1]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import pandas as pd

In [35]:
documents = [
    "This is NLP NLP session",
    "nlp uses machine learning",
    "NLP uses deep deep learning"
]

In [3]:
cv = CountVectorizer()

In [4]:
cv = CountVectorizer(stop_words = "english")

In [5]:
cv.fit(documents)

CountVectorizer(stop_words='english')

In [6]:
cv.vocabulary_

{'nlp': 3, 'session': 4, 'uses': 5, 'machine': 2, 'learning': 1, 'deep': 0}

In [7]:
vocab = sorted(cv.vocabulary_.keys())

In [10]:
doc_vector= cv.transform(documents).toarray()

In [11]:
doc_vector

array([[0, 0, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 1],
       [1, 1, 0, 1, 0, 1]])

In [12]:
df =pd.DataFrame(doc_vector,columns = vocab)

In [13]:
df

   deep  learning  machine  nlp  session  uses
0     0         0        0    1        1     0
1     0         1        1    1        0     1
2     1         1        0    1        0     1

TF-IDF

In [36]:

tfidf = TfidfVectorizer(stop_words="english")

In [37]:
tfidf.fit(documents)

TfidfVectorizer(stop_words='english')

In [38]:
vocab = sorted(tfidf.vocabulary_.keys())

In [39]:
doc_vector = tfidf.transform(documents).toarray()

In [40]:

df = pd.DataFrame(doc_vector, columns=vocab)
df

       deep  learning   machine       nlp   session      uses
0  0.000000  0.000000  0.000000  0.763228  0.646129  0.000000
1  0.000000  0.480458  0.631745  0.373119  0.000000  0.480458
2  0.852367  0.324124  0.000000  0.251711  0.000000  0.324124

In [41]:
## Embeddings :: Embeddings in NLP refer to a dense vector representation of words or other textual units (like sentences or documents)
## in a continuous vector space, where semantically similar words are mapped closer together.
# Popular Embedding Methods
# 	1.	Word2Vec (Google)
# 	•	Trained using Continuous Bag of Words (CBOW) or Skip-gram models.
# 	•	Example: “king - man + woman ≈ queen”
# 	2.	GloVe (Global Vectors by Stanford)
# 	•	Trained on word co-occurrence statistics from a large corpus.
# 	•	Captures both local and global statistical relationships.
# 	3.	FastText (Facebook)
# 	•	Extends Word2Vec by using character n-grams, making it better for rare and morphologically complex words.
# 	4.	BERT (Bidirectional Encoder Representations from Transformers by Google)
# 	•	Contextual embeddings based on transformer architecture.
# 	•	“Apple” can have different embeddings depending on whether it refers to the fruit or the company.
# 	5.	GPT Embeddings (OpenAI)
# 	•	Contextual embeddings useful for complex text understanding and generation tasks.

In [43]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 40.6 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [44]:
import gensim

In [45]:
import gensim.downloader as api
w= api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [46]:
w["king"]

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [47]:
w["king"].shape

(300,)

In [48]:
w.similar_by_word("dog")

[('dogs', 0.8680489659309387),
 ('puppy', 0.8106428384780884),
 ('pit_bull', 0.780396044254303),
 ('pooch', 0.7627376914024353),
 ('cat', 0.7609457969665527),
 ('golden_retriever', 0.7500901818275452),
 ('German_shepherd', 0.7465174198150635),
 ('Rottweiler', 0.7437615394592285),
 ('beagle', 0.7418621778488159),
 ('pup', 0.740691065788269)]

In [54]:
w.doesnt_match(["cat","lion","tiger","dog"])

'lion'

In [59]:
w.most_similar(
    positive =["king","women"],
    negative =["man"],
    topn = 1
)

[('queen', 0.4827326238155365)]

In [60]:
w.most_similar(
    positive =["queen","man"],
    negative =["woman"],
    topn = 1
)

[('king', 0.6958590149879456)]